---
- name: Manage volume groups and logical volumes
  hosts: all
  tasks:
    - name: create 1st partition
      community.general.parted:  
        device: /dev/vdb
        number: 1       #1st partition will created  
        state: present
        label: gpt #gpt disk will created
        flags: lvm    # this will mentioned lvm flags for the device
        part_start: 0%
        part_end: 30%
      when: inventory_hostname in ['servera.lab.example.com', 'serverc.lab.example.com']

    - name: create 2nd partition
      community.general.parted:
        device: /dev/vdb
        number: 2
        state: present
        label: gpt
        flags: lvm
        part_start: 31%
        part_end: 100%
      when: inventory_hostname in ['servera.lab.example.com', 'serverc.lab.example.com']
    
    - name: Create volumes group on all applicable machines
      community.general.lvg:
        vg: research
        pvs: /dev/vdb2
      when: inventory_hostname == 'servera.lab.example.com'

    - name: create volume group in serverc
      community.general.lvg:
        vg: research
        pvs: /dev/vdb1
      when: inventory_hostname == 'serverc.lab.example.com'
