---
  - name: demo of facts
    hosts: webservers
    gather_facts: false
    tasks:
      - name: collect host information
        ansible.builtin.setup:

      - name: print memory information
        ansible.builtin.debug:
          msg: The avaiable memory in {{ ansible_facts['hostname'] }} is {{ ansible_facts['memtotal_mb'] }} MB

      - name: print storage information
        ansible.builtin.debug:
          msg: The avaible storage in {{ ansible_facts['hostname'] }} is {{ ansible_facts['devices']['vda']['size'] }} GB
