---
  - name: testing fetch module
    hosts: dbservers
    tasks:
      - name: get logs of webservers machine
        ansible.builtin.fetch:
          src: /var/log/secure
          dest: /home/student/ansible/remote_data/dbserver
          flat: true
