---
  - name: configuring webservers
    hosts: dbservers
    tasks:
      - name: install packages
        ansible.builtin.dnf:
          name:
            - httpd
            - firewalld
          state: latest

      - name: start service
        ansible.builtin.service:
          name: "{{ item }}"
          state: started
          enabled: true
        loop:
          - httpd
          - firewalld
      
      - name: configure http file
        ansible.builtin.copy:
          content: "Hello! Welcome to the world of OpenShift"
          dest: /var/www/html/index.html
        notify: restart_service

      - name: configure firewall
        ansible.posix.firewalld:
          service: http
          state: enabled
          immediate: true
          permanent: true

    handlers:
      - name: restart_service
        ansible.builtin.service:
          name: httpd
          state: restarted
