---
  - name: testing ignore_errors
    hosts: serverd.lab.example.com
    #force_handlers: true
    ignore_errors: true
    tasks:
      - name: task-1
        ansible.builtin.command:
          cmd: free -h

      - name: task-2
        ansible.builtin.command:
          cmd: ls
        notify: handler1

      - name: tasks3
        ansible.builtin.command:
          cmd: hostname
    
    handlers:
      - name: handler10
        ansible.builtin.command:
          cmd: lsblk
        
