---
  - name: creating hosts file in servera
    hosts: appservers
    tasks:
      - name: deploy the host file
        ansible.builtin.template:
          src: hosts.j2
          dest: /etc/hosts
        when: inventory_hostname == 'servera.lab.example.com'

