---
  - name: installing packages and service using loop
    hosts: webservers
    tasks:
      - name: install the packages
        ansible.builtin.dnf:
          name:
            - httpd
            - firewalld
          state: latest

      - name: start the service
        ansible.builtin.service:
          name: '{{ item }}'
          state: started
          enabled: true
        loop:
          - httpd
          - firewalld
          
