---
  - name: executing roles and tasks
    hosts: servera.lab.example.com
    tasks:
      - name: general tasks
        ansible.builtin.command:
          cmd: free -h
      - name: roles tasks
        ansible.builtin.include_role: 
          name: myrole
